name: session_list
author: Arnaud Kientz
email: arnaud@unpeud.info
url: https://github.com/kiarn/ajenti-plugins
version: '0.2'
title: 'Session list'
icon: network-wired
dependencies:
    - !!python/object:aj.plugins.PluginDependency { plugin_name: core }
resources:
    - resources/js/module.es
    - resources/js/routing.es
    - resources/js/controllers/index.controller.coffee
    - resources/partial/index.html
    - ng:session_list
